alter table recruit.application
    add column final_status varchar(20),
    add column final_decided_at timestamptz,
    add column final_note text;

alter table recruit.application
    add constraint application_final_status_ck
        check (final_status in ('OFFER_MADE', 'ACCEPTED', 'DECLINED', 'WITHDRAWN'));

create table recruit.notification_log (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    type            varchar(40) not null,
    title           varchar(200) not null,
    content         text not null,
    sent_by         bigint references platform.admin_account(id),
    created_at      timestamptz not null default current_timestamp
);

create index notification_log_app_idx
    on recruit.notification_log(application_id);
