create table platform.permission (
    id      bigint generated by default as identity primary key,
    code    varchar(60) not null unique,
    name    varchar(120) not null
);

create table platform.role_permission (
    role            varchar(40) not null,
    permission_id   bigint not null references platform.permission(id) on delete cascade,
    primary key (role, permission_id)
);

insert into platform.permission (code, name) values
    ('APPLICANT_VIEW', '지원자 조회'),
    ('APPLICANT_REVIEW', '지원자 검토'),
    ('INTERVIEW_MANAGE', '면접 관리'),
    ('EVALUATION_WRITE', '평가 작성'),
    ('FINAL_DECIDE', '최종 합격 결정'),
    ('NOTIFICATION_SEND', '통지 발송'),
    ('ADMIN_MANAGE', '관리자 관리');

-- SUPER_ADMIN: 전체 권한
insert into platform.role_permission (role, permission_id)
    select 'SUPER_ADMIN', id from platform.permission;

-- ADMIN: 조회 + 평가만
insert into platform.role_permission (role, permission_id)
    select 'ADMIN', id from platform.permission
    where code in ('APPLICANT_VIEW', 'EVALUATION_WRITE');
