create table recruit.legacy_mapping (
    id              bigint generated by default as identity primary key,
    entity_type     varchar(40) not null,
    legacy_key      varchar(200) not null,
    new_id          bigint not null,
    migrated_at     timestamptz not null default current_timestamp,
    notes           text,
    constraint legacy_mapping_unique unique (entity_type, legacy_key)
);

create table recruit.migration_run (
    id              bigint generated by default as identity primary key,
    run_name        varchar(200) not null,
    status          varchar(20) not null default 'RUNNING',
    total_count     integer,
    success_count   integer default 0,
    fail_count      integer default 0,
    started_at      timestamptz not null default current_timestamp,
    completed_at    timestamptz,
    error_log       text,
    constraint migration_run_status_ck check (status in ('RUNNING', 'COMPLETED', 'FAILED'))
);
