create table platform.candidate_account (
    id bigint generated by default as identity primary key,
    email varchar(160) not null,
    normalized_email varchar(160) not null unique,
    display_name varchar(120) not null,
    phone_number varchar(40) not null,
    password_hash text not null,
    status varchar(20) not null,
    last_authenticated_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint candidate_account_status_ck check (status in ('ACTIVE', 'LOCKED'))
);

create table platform.candidate_session (
    id bigint generated by default as identity primary key,
    candidate_account_id bigint not null references platform.candidate_account(id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    last_seen_at timestamptz,
    invalidated_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create index candidate_session_account_idx
    on platform.candidate_session(candidate_account_id);

create index candidate_session_expires_idx
    on platform.candidate_session(expires_at);

alter table recruit.application
    add column candidate_account_id bigint references platform.candidate_account(id);

create index application_candidate_account_idx
    on recruit.application(candidate_account_id);

create unique index application_job_posting_candidate_uidx
    on recruit.application(candidate_account_id, job_posting_id)
    where candidate_account_id is not null;