insert into recruit.job_posting (
    id,
    legacy_anno_id,
    public_key,
    title,
    headline,
    description,
    employment_type,
    location,
    status,
    published,
    opens_at,
    closes_at
)
values
    (1003, 90103, 'hr-talent-acquisition-partner', 'HR Talent Acquisition Partner', 'Own full-cycle hiring operations for core teams.', 'Lead sourcing coordination, pipeline hygiene, and hiring manager alignment across growing business functions.', 'FULL_TIME', 'Seoul', 'OPEN', true, current_timestamp - interval '4 day', current_timestamp + interval '18 day'),
    (1004, 90104, 'people-operations-specialist', 'People Operations Specialist', 'Stabilize day-to-day people operations and onboarding.', 'Support onboarding, HR documentation, and recurring people programs for a fast-moving recruiting team.', 'CONTRACT', 'Seoul', 'OPEN', true, current_timestamp - interval '2 day', current_timestamp + interval '16 day'),
    (1005, 90105, 'frontend-engineer-react', 'Frontend Engineer (React)', 'Build a clear applicant and admin web experience.', 'Ship Next.js and React interfaces for job discovery, applications, and recruiter workflows.', 'FULL_TIME', 'Seoul', 'OPEN', true, current_timestamp - interval '5 day', current_timestamp + interval '20 day'),
    (1006, 90106, 'qa-automation-engineer', 'QA Automation Engineer', 'Keep the recruiting workflow stable as the product scales.', 'Design regression coverage, automate critical paths, and harden release confidence for hiring operations.', 'CONTRACT', 'Busan', 'OPEN', true, current_timestamp - interval '3 day', current_timestamp + interval '17 day'),
    (1007, 90107, 'data-analyst-recruiting', 'Data Analyst, Recruiting', 'Turn recruiting activity into operational insight.', 'Build reporting, funnel analysis, and weekly hiring metrics that help teams act on bottlenecks.', 'CONTRACT', 'Seoul', 'OPEN', true, current_timestamp - interval '1 day', current_timestamp + interval '15 day'),
    (1008, 90108, 'sales-account-executive', 'Sales Account Executive', 'Own outbound pipeline creation and revenue conversations.', 'Prospect target accounts, qualify demand, and move mid-market customers through the sales cycle.', 'FULL_TIME', 'Seoul', 'OPEN', true, current_timestamp - interval '6 day', current_timestamp + interval '22 day'),
    (1009, 90109, 'sales-operations-analyst', 'Sales Operations Analyst', 'Make pipeline data and forecasting reliable.', 'Maintain CRM discipline, improve reporting, and support territory and pipeline planning with the sales team.', 'CONTRACT', 'Seoul', 'OPEN', true, current_timestamp - interval '2 day', current_timestamp + interval '19 day'),
    (1010, 90110, 'office-support-coordinator', 'Office Support Coordinator', 'Keep office operations and documents on track.', 'Coordinate contracts, schedules, vendor communication, and office support work across shared services.', 'CONTRACT', 'Incheon', 'OPEN', true, current_timestamp - interval '3 day', current_timestamp + interval '14 day'),
    (1011, 90111, 'finance-operations-associate', 'Finance Operations Associate', 'Own day-to-day finance operations with precision.', 'Support invoice handling, closing schedules, payment tracking, and operations reporting for the business.', 'FULL_TIME', 'Seoul', 'OPEN', true, current_timestamp - interval '4 day', current_timestamp + interval '18 day'),
    (1012, 90112, 'crm-marketing-specialist', 'CRM Marketing Specialist', 'Run lifecycle messaging that improves conversion.', 'Manage segmented campaigns, automate follow-ups, and improve candidate and customer communication touchpoints.', 'CONTRACT', 'Seoul', 'OPEN', true, current_timestamp - interval '1 day', current_timestamp + interval '12 day'),
    (1013, 90113, 'it-support-engineer', 'IT Support Engineer', 'Support devices, accounts, and internal tools.', 'Handle endpoint setup, access requests, and daily IT support issues for the office and recruiting staff.', 'CONTRACT', 'Daejeon', 'OPEN', true, current_timestamp - interval '2 day', current_timestamp + interval '24 day'),
    (1014, 90114, 'security-engineer', 'Security Engineer', 'Strengthen application and infrastructure trust boundaries.', 'Improve application security posture, secrets handling, and access controls across internal systems.', 'FULL_TIME', 'Seoul', 'OPEN', true, current_timestamp - interval '1 day', current_timestamp + interval '25 day'),
    (1015, 90115, 'customer-experience-manager', 'Customer Experience Manager', 'Own customer communication quality after onboarding.', 'Drive service communication, feedback loops, and structured issue follow-up for long-term retention.', 'FULL_TIME', 'Busan', 'OPEN', true, current_timestamp - interval '2 day', current_timestamp + interval '24 day'),
    (1016, 90116, 'hr-generalist', 'HR Generalist', 'Cover hiring support and core people operations.', 'Partner with hiring managers and employees across recruiting support, policy operations, and documentation.', 'FULL_TIME', 'Seoul', 'CLOSED', true, current_timestamp - interval '26 day', current_timestamp - interval '1 day'),
    (1017, 90117, 'field-sales-manager', 'Field Sales Manager', 'Lead field sales execution in regional accounts.', 'Own account visits, enterprise relationship building, and late-stage deal execution with regional prospects.', 'FULL_TIME', 'Daegu', 'CLOSED', true, current_timestamp - interval '35 day', current_timestamp - interval '4 day'),
    (1018, 90118, 'recruiting-coordinator', 'Recruiting Coordinator', 'Coordinate interviews and candidate communication.', 'Run scheduling, interview logistics, and candidate updates so hiring loops stay reliable and fast.', 'CONTRACT', 'Seoul', 'CLOSED', true, current_timestamp - interval '32 day', current_timestamp - interval '5 day'),
    (1019, 90119, 'executive-assistant', 'Executive Assistant', 'Support leadership operations and scheduling.', 'Manage calendars, meeting preparation, internal follow-ups, and executive support routines.', 'CONTRACT', 'Seoul', 'CLOSED', true, current_timestamp - interval '28 day', current_timestamp - interval '3 day'),
    (1020, 90120, 'procurement-asset-coordinator', 'Procurement and Asset Coordinator', 'Own purchasing operations and asset tracking.', 'Coordinate purchasing requests, vendor follow-up, and office asset lifecycle tracking across teams.', 'FULL_TIME', 'Incheon', 'CLOSED', true, current_timestamp - interval '30 day', current_timestamp - interval '6 day');

insert into recruit.job_posting_step (
    id,
    job_posting_id,
    step_order,
    step_type,
    title,
    description,
    starts_at,
    ends_at
)
values
    (2007, 1003, 1, 'DOCUMENT', 'Document Review', 'Review hiring operations experience and stakeholder coordination.', current_timestamp - interval '4 day', current_timestamp + interval '3 day'),
    (2008, 1003, 2, 'INTERVIEW', 'Recruiting Interview', 'Discuss sourcing process, hiring manager alignment, and pipeline ownership.', current_timestamp + interval '4 day', current_timestamp + interval '9 day'),
    (2009, 1003, 3, 'INTERVIEW', 'Leadership Interview', 'Assess prioritization and communication in cross-functional recruiting work.', current_timestamp + interval '10 day', current_timestamp + interval '13 day'),
    (2010, 1003, 4, 'OFFER', 'Offer Discussion', 'Align compensation, start date, and team expectations.', current_timestamp + interval '14 day', current_timestamp + interval '18 day'),
    (2011, 1004, 1, 'DOCUMENT', 'Document Review', 'Review people operations experience, process discipline, and documentation quality.', current_timestamp - interval '2 day', current_timestamp + interval '4 day'),
    (2012, 1004, 2, 'INTERVIEW', 'Operations Interview', 'Assess onboarding support, policy handling, and stakeholder communication.', current_timestamp + interval '5 day', current_timestamp + interval '8 day'),
    (2013, 1004, 3, 'INTERVIEW', 'Team Interview', 'Validate collaboration style and execution reliability.', current_timestamp + interval '9 day', current_timestamp + interval '12 day'),
    (2014, 1004, 4, 'OFFER', 'Contract Discussion', 'Review contract terms, start timing, and working expectations.', current_timestamp + interval '13 day', current_timestamp + interval '16 day'),
    (2015, 1005, 1, 'DOCUMENT', 'Document Review', 'Review product delivery history and frontend implementation depth.', current_timestamp - interval '5 day', current_timestamp + interval '2 day'),
    (2016, 1005, 2, 'ASSIGNMENT', 'Frontend Exercise', 'Assess UI implementation quality, state handling, and delivery judgment.', current_timestamp + interval '3 day', current_timestamp + interval '7 day'),
    (2017, 1005, 3, 'INTERVIEW', 'Technical Interview', 'Discuss Next.js architecture, quality practices, and collaboration style.', current_timestamp + interval '8 day', current_timestamp + interval '12 day'),
    (2018, 1005, 4, 'OFFER', 'Offer Discussion', 'Align scope, compensation, and onboarding plan.', current_timestamp + interval '13 day', current_timestamp + interval '20 day'),
    (2019, 1006, 1, 'DOCUMENT', 'Document Review', 'Review test automation depth and release ownership experience.', current_timestamp - interval '3 day', current_timestamp + interval '4 day'),
    (2020, 1006, 2, 'ASSIGNMENT', 'Automation Exercise', 'Assess regression design, test strategy, and failure analysis.', current_timestamp + interval '5 day', current_timestamp + interval '8 day'),
    (2021, 1006, 3, 'INTERVIEW', 'QA Interview', 'Discuss quality strategy, tooling, and defect prevention approaches.', current_timestamp + interval '9 day', current_timestamp + interval '12 day'),
    (2022, 1006, 4, 'OFFER', 'Contract Discussion', 'Confirm engagement scope, contract duration, and start date.', current_timestamp + interval '13 day', current_timestamp + interval '17 day'),
    (2023, 1007, 1, 'DOCUMENT', 'Document Review', 'Review analysis depth, reporting experience, and stakeholder support.', current_timestamp - interval '1 day', current_timestamp + interval '3 day'),
    (2024, 1007, 2, 'ASSIGNMENT', 'Analytics Exercise', 'Assess reporting structure, metric reasoning, and decision support.', current_timestamp + interval '4 day', current_timestamp + interval '6 day'),
    (2025, 1007, 3, 'INTERVIEW', 'Analyst Interview', 'Discuss funnel analysis, reporting cadence, and communication style.', current_timestamp + interval '7 day', current_timestamp + interval '11 day'),
    (2026, 1007, 4, 'OFFER', 'Contract Discussion', 'Align scope, reporting ownership, and contract terms.', current_timestamp + interval '12 day', current_timestamp + interval '15 day'),
    (2027, 1008, 1, 'DOCUMENT', 'Document Review', 'Review quota attainment, account strategy, and sales execution evidence.', current_timestamp - interval '6 day', current_timestamp + interval '3 day'),
    (2028, 1008, 2, 'INTERVIEW', 'Sales Interview', 'Discuss pipeline generation, qualification, and customer conversations.', current_timestamp + interval '4 day', current_timestamp + interval '9 day'),
    (2029, 1008, 3, 'INTERVIEW', 'Leadership Interview', 'Assess forecast ownership, execution rhythm, and collaboration with operations.', current_timestamp + interval '10 day', current_timestamp + interval '15 day'),
    (2030, 1008, 4, 'OFFER', 'Offer Discussion', 'Review compensation mix, territory scope, and start plan.', current_timestamp + interval '16 day', current_timestamp + interval '22 day'),
    (2031, 1009, 1, 'DOCUMENT', 'Document Review', 'Review CRM discipline, reporting depth, and operations support experience.', current_timestamp - interval '2 day', current_timestamp + interval '5 day'),
    (2032, 1009, 2, 'INTERVIEW', 'Operations Interview', 'Discuss forecast hygiene, reporting ownership, and process improvement.', current_timestamp + interval '6 day', current_timestamp + interval '10 day'),
    (2033, 1009, 3, 'INTERVIEW', 'Team Interview', 'Assess prioritization and communication with sales leadership.', current_timestamp + interval '11 day', current_timestamp + interval '15 day'),
    (2034, 1009, 4, 'OFFER', 'Contract Discussion', 'Confirm contract scope, reporting cadence, and handoff plan.', current_timestamp + interval '16 day', current_timestamp + interval '19 day'),
    (2035, 1010, 1, 'DOCUMENT', 'Document Review', 'Review office support experience and document handling quality.', current_timestamp - interval '3 day', current_timestamp + interval '2 day'),
    (2036, 1010, 2, 'INTERVIEW', 'Operations Interview', 'Discuss scheduling, vendor communication, and office support routines.', current_timestamp + interval '3 day', current_timestamp + interval '7 day'),
    (2037, 1010, 3, 'INTERVIEW', 'Team Interview', 'Assess reliability, service mindset, and communication discipline.', current_timestamp + interval '8 day', current_timestamp + interval '11 day'),
    (2038, 1010, 4, 'OFFER', 'Contract Discussion', 'Review contract terms, shift expectations, and start timing.', current_timestamp + interval '12 day', current_timestamp + interval '14 day'),
    (2039, 1011, 1, 'DOCUMENT', 'Document Review', 'Review finance operations accuracy and close-cycle experience.', current_timestamp - interval '4 day', current_timestamp + interval '4 day'),
    (2040, 1011, 2, 'INTERVIEW', 'Finance Interview', 'Discuss payment handling, reporting, and deadline management.', current_timestamp + interval '5 day', current_timestamp + interval '9 day'),
    (2041, 1011, 3, 'INTERVIEW', 'Team Interview', 'Assess operating style, attention to detail, and stakeholder support.', current_timestamp + interval '10 day', current_timestamp + interval '14 day'),
    (2042, 1011, 4, 'OFFER', 'Offer Discussion', 'Align compensation, responsibilities, and onboarding timing.', current_timestamp + interval '15 day', current_timestamp + interval '18 day'),
    (2043, 1012, 1, 'DOCUMENT', 'Document Review', 'Review CRM campaign ownership and automation experience.', current_timestamp - interval '1 day', current_timestamp + interval '2 day'),
    (2044, 1012, 2, 'ASSIGNMENT', 'Campaign Exercise', 'Assess segmentation logic, message planning, and execution quality.', current_timestamp + interval '3 day', current_timestamp + interval '6 day'),
    (2045, 1012, 3, 'INTERVIEW', 'Marketing Interview', 'Discuss lifecycle messaging, analytics, and stakeholder alignment.', current_timestamp + interval '7 day', current_timestamp + interval '10 day'),
    (2046, 1012, 4, 'OFFER', 'Contract Discussion', 'Confirm campaign scope, contract terms, and start plan.', current_timestamp + interval '11 day', current_timestamp + interval '12 day'),
    (2047, 1013, 1, 'DOCUMENT', 'Document Review', 'Review helpdesk, device setup, and access management experience.', current_timestamp - interval '2 day', current_timestamp + interval '3 day'),
    (2048, 1013, 2, 'INTERVIEW', 'IT Support Interview', 'Discuss endpoint support, ticket handling, and internal communication.', current_timestamp + interval '4 day', current_timestamp + interval '8 day'),
    (2049, 1013, 3, 'INTERVIEW', 'Team Interview', 'Assess troubleshooting habits and service reliability.', current_timestamp + interval '9 day', current_timestamp + interval '11 day'),
    (2050, 1013, 4, 'OFFER', 'Contract Discussion', 'Review support schedule, contract duration, and onboarding needs.', current_timestamp + interval '12 day', current_timestamp + interval '13 day'),
    (2051, 1014, 1, 'DOCUMENT', 'Document Review', 'Review application security depth and operational ownership.', current_timestamp - interval '1 day', current_timestamp + interval '8 day'),
    (2052, 1014, 2, 'ASSIGNMENT', 'Security Exercise', 'Assess risk analysis, control design, and incident reasoning.', current_timestamp + interval '9 day', current_timestamp + interval '14 day'),
    (2053, 1014, 3, 'INTERVIEW', 'Security Interview', 'Discuss trust boundaries, secure defaults, and delivery tradeoffs.', current_timestamp + interval '15 day', current_timestamp + interval '20 day'),
    (2054, 1014, 4, 'OFFER', 'Offer Discussion', 'Confirm scope, compensation, and start timing.', current_timestamp + interval '21 day', current_timestamp + interval '25 day'),
    (2055, 1015, 1, 'DOCUMENT', 'Document Review', 'Review customer communication, retention support, and escalation handling.', current_timestamp - interval '2 day', current_timestamp + interval '4 day'),
    (2056, 1015, 2, 'INTERVIEW', 'Customer Interview', 'Discuss service operations, issue follow-up, and account coordination.', current_timestamp + interval '5 day', current_timestamp + interval '9 day'),
    (2057, 1015, 3, 'INTERVIEW', 'Leadership Interview', 'Assess prioritization, communication quality, and process discipline.', current_timestamp + interval '10 day', current_timestamp + interval '14 day'),
    (2058, 1015, 4, 'OFFER', 'Offer Discussion', 'Align ownership scope, compensation, and onboarding timing.', current_timestamp + interval '15 day', current_timestamp + interval '24 day'),
    (2059, 1016, 1, 'DOCUMENT', 'Document Review', 'Review HR operations breadth and business support experience.', current_timestamp - interval '26 day', current_timestamp - interval '20 day'),
    (2060, 1016, 2, 'INTERVIEW', 'HR Interview', 'Discuss employee support, policy handling, and recruiting coordination.', current_timestamp - interval '19 day', current_timestamp - interval '13 day'),
    (2061, 1016, 3, 'INTERVIEW', 'Leadership Interview', 'Assess judgment, prioritization, and communication patterns.', current_timestamp - interval '12 day', current_timestamp - interval '6 day'),
    (2062, 1016, 4, 'OFFER', 'Offer Discussion', 'Final offer and onboarding discussion completed before close.', current_timestamp - interval '5 day', current_timestamp - interval '1 day'),
    (2063, 1017, 1, 'DOCUMENT', 'Document Review', 'Review regional pipeline performance and account ownership.', current_timestamp - interval '35 day', current_timestamp - interval '28 day'),
    (2064, 1017, 2, 'INTERVIEW', 'Sales Interview', 'Discuss field execution, enterprise meetings, and late-stage deals.', current_timestamp - interval '27 day', current_timestamp - interval '20 day'),
    (2065, 1017, 3, 'INTERVIEW', 'Leadership Interview', 'Assess planning discipline and regional execution style.', current_timestamp - interval '19 day', current_timestamp - interval '12 day'),
    (2066, 1017, 4, 'OFFER', 'Offer Discussion', 'Offer process closed after compensation and territory review.', current_timestamp - interval '11 day', current_timestamp - interval '4 day'),
    (2067, 1018, 1, 'DOCUMENT', 'Document Review', 'Review scheduling ownership and candidate communication quality.', current_timestamp - interval '32 day', current_timestamp - interval '25 day'),
    (2068, 1018, 2, 'INTERVIEW', 'Coordinator Interview', 'Discuss interview logistics, responsiveness, and process discipline.', current_timestamp - interval '24 day', current_timestamp - interval '18 day'),
    (2069, 1018, 3, 'INTERVIEW', 'Team Interview', 'Assess collaboration style and operating consistency.', current_timestamp - interval '17 day', current_timestamp - interval '11 day'),
    (2070, 1018, 4, 'OFFER', 'Contract Discussion', 'Contract process completed before posting close.', current_timestamp - interval '10 day', current_timestamp - interval '5 day'),
    (2071, 1019, 1, 'DOCUMENT', 'Document Review', 'Review executive support depth and schedule management.', current_timestamp - interval '28 day', current_timestamp - interval '21 day'),
    (2072, 1019, 2, 'INTERVIEW', 'Operations Interview', 'Discuss calendar management, meeting preparation, and follow-up discipline.', current_timestamp - interval '20 day', current_timestamp - interval '14 day'),
    (2073, 1019, 3, 'INTERVIEW', 'Leadership Interview', 'Assess communication judgment and support style for leadership partners.', current_timestamp - interval '13 day', current_timestamp - interval '7 day'),
    (2074, 1019, 4, 'OFFER', 'Contract Discussion', 'Offer and contract closed after executive support review.', current_timestamp - interval '6 day', current_timestamp - interval '3 day'),
    (2075, 1020, 1, 'DOCUMENT', 'Document Review', 'Review purchasing coordination and asset tracking experience.', current_timestamp - interval '30 day', current_timestamp - interval '23 day'),
    (2076, 1020, 2, 'INTERVIEW', 'Operations Interview', 'Discuss vendor follow-up, purchase requests, and inventory processes.', current_timestamp - interval '22 day', current_timestamp - interval '16 day'),
    (2077, 1020, 3, 'INTERVIEW', 'Team Interview', 'Assess process rigor, cross-team communication, and execution quality.', current_timestamp - interval '15 day', current_timestamp - interval '9 day'),
    (2078, 1020, 4, 'OFFER', 'Offer Discussion', 'Offer process completed before the posting was closed.', current_timestamp - interval '8 day', current_timestamp - interval '6 day');

select setval('recruit.job_posting_id_seq', (select max(id) from recruit.job_posting));
select setval('recruit.job_posting_step_id_seq', (select max(id) from recruit.job_posting_step));
