create table platform.candidate_profile (
    candidate_account_id        bigint primary key references platform.candidate_account(id) on delete cascade,
    introduction_template       text,
    core_strength_template      text,
    career_years                integer,
    updated_at                  timestamptz not null default current_timestamp
);

create table platform.candidate_profile_education (
    id                      bigint generated by default as identity primary key,
    candidate_account_id    bigint not null references platform.candidate_account(id) on delete cascade,
    institution             varchar(200) not null,
    degree                  varchar(40),
    field_of_study          varchar(200),
    start_date              date,
    end_date                date,
    description             text,
    sort_order              int not null default 0,
    created_at              timestamptz not null default current_timestamp,
    updated_at              timestamptz not null default current_timestamp
);

create index candidate_profile_education_account_idx
    on platform.candidate_profile_education(candidate_account_id);

create table platform.candidate_profile_experience (
    id                      bigint generated by default as identity primary key,
    candidate_account_id    bigint not null references platform.candidate_account(id) on delete cascade,
    company                 varchar(200) not null,
    position                varchar(200),
    start_date              date,
    end_date                date,
    description             text,
    sort_order              int not null default 0,
    created_at              timestamptz not null default current_timestamp,
    updated_at              timestamptz not null default current_timestamp
);

create index candidate_profile_experience_account_idx
    on platform.candidate_profile_experience(candidate_account_id);

create table platform.candidate_profile_skill (
    id                      bigint generated by default as identity primary key,
    candidate_account_id    bigint not null references platform.candidate_account(id) on delete cascade,
    skill_name              varchar(100) not null,
    proficiency             varchar(30),
    years                   int,
    sort_order              int not null default 0,
    created_at              timestamptz not null default current_timestamp,
    updated_at              timestamptz not null default current_timestamp
);

create index candidate_profile_skill_account_idx
    on platform.candidate_profile_skill(candidate_account_id);

create table platform.candidate_profile_certification (
    id                      bigint generated by default as identity primary key,
    candidate_account_id    bigint not null references platform.candidate_account(id) on delete cascade,
    certification_name      varchar(200) not null,
    issuer                  varchar(200),
    issued_date             date,
    expiry_date             date,
    sort_order              int not null default 0,
    created_at              timestamptz not null default current_timestamp,
    updated_at              timestamptz not null default current_timestamp
);

create index candidate_profile_certification_account_idx
    on platform.candidate_profile_certification(candidate_account_id);

create table platform.candidate_profile_language (
    id                      bigint generated by default as identity primary key,
    candidate_account_id    bigint not null references platform.candidate_account(id) on delete cascade,
    language_name           varchar(60) not null,
    proficiency             varchar(30),
    test_name               varchar(100),
    test_score              varchar(40),
    sort_order              int not null default 0,
    created_at              timestamptz not null default current_timestamp,
    updated_at              timestamptz not null default current_timestamp
);

create index candidate_profile_language_account_idx
    on platform.candidate_profile_language(candidate_account_id);
