create table recruit.job_posting_question (
    id              bigint generated by default as identity primary key,
    job_posting_id  bigint not null references recruit.job_posting(id) on delete cascade,
    question_text   text not null,
    question_type   varchar(20) not null,
    choices         jsonb,
    required        boolean not null default true,
    sort_order      int not null default 0,
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp,
    constraint job_posting_question_type_ck check (question_type in ('TEXT', 'CHOICE', 'SCALE'))
);

create index job_posting_question_posting_idx
    on recruit.job_posting_question(job_posting_id);

create table recruit.application_answer (
    id                          bigint generated by default as identity primary key,
    application_id              bigint not null references recruit.application(id) on delete cascade,
    job_posting_question_id     bigint not null references recruit.job_posting_question(id) on delete cascade,
    answer_text                 text,
    answer_choice               varchar(200),
    answer_scale                smallint,
    created_at                  timestamptz not null default current_timestamp,
    updated_at                  timestamptz not null default current_timestamp,
    constraint application_answer_uidx unique (application_id, job_posting_question_id)
);

create index application_answer_application_idx
    on recruit.application_answer(application_id);
