create table recruit.job_posting (
    id bigint generated by default as identity primary key,
    legacy_anno_id bigint,
    public_key varchar(80) not null unique,
    title varchar(200) not null,
    headline varchar(200) not null,
    description text not null,
    employment_type varchar(40) not null,
    location varchar(120) not null,
    status varchar(20) not null,
    published boolean not null default true,
    opens_at timestamptz not null,
    closes_at timestamptz not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint job_posting_status_ck check (status in ('DRAFT', 'OPEN', 'CLOSED'))
);

create table recruit.job_posting_step (
    id bigint generated by default as identity primary key,
    job_posting_id bigint not null references recruit.job_posting(id) on delete cascade,
    step_order smallint not null,
    step_type varchar(40) not null,
    title varchar(120) not null,
    description text not null,
    starts_at timestamptz,
    ends_at timestamptz,
    constraint job_posting_step_type_ck check (step_type in ('DOCUMENT', 'ASSIGNMENT', 'INTERVIEW', 'OFFER'))
);

create unique index job_posting_step_order_uidx
    on recruit.job_posting_step(job_posting_id, step_order);

create table recruit.application (
    id bigint generated by default as identity primary key,
    job_posting_id bigint not null references recruit.job_posting(id) on delete restrict,
    applicant_name varchar(120) not null,
    applicant_email varchar(160) not null,
    applicant_phone varchar(40) not null,
    status varchar(20) not null,
    draft_saved_at timestamptz not null,
    submitted_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint application_status_ck check (status in ('DRAFT', 'SUBMITTED'))
);

create unique index application_job_posting_email_uidx
    on recruit.application(job_posting_id, lower(applicant_email));

create table recruit.application_resume_raw (
    application_id bigint primary key references recruit.application(id) on delete cascade,
    payload jsonb not null,
    updated_at timestamptz not null default current_timestamp
);

insert into recruit.job_posting (
    id,
    legacy_anno_id,
    public_key,
    title,
    headline,
    description,
    employment_type,
    location,
    status,
    published,
    opens_at,
    closes_at
)
values
    (
        1001,
        90101,
        'platform-backend-engineer',
        'Platform Backend Engineer',
        '채용 운영과 지원 경험을 동시에 안정화할 백엔드 엔지니어를 찾습니다.',
        '레거시 채용 시스템을 PostgreSQL-first 구조로 전환하는 팀입니다. 공고, 지원서, 평가, 통지 도메인을 재구성하고 운영 안정성을 높이는 백엔드 엔지니어를 찾습니다.',
        'FULL_TIME',
        'Seoul',
        'OPEN',
        true,
        current_timestamp - interval '3 day',
        current_timestamp + interval '21 day'
    ),
    (
        1002,
        90102,
        'product-designer',
        'Product Designer',
        '지원자 경험과 운영자 흐름을 함께 설계할 프로덕트 디자이너를 찾습니다.',
        '지원자 여정과 채용 운영 화면을 재설계하는 역할입니다. 공고 노출, 지원 작성, 평가 리뷰 UX를 설계할 수 있는 디자이너를 찾습니다.',
        'CONTRACT',
        'Seoul',
        'CLOSED',
        true,
        current_timestamp - interval '40 day',
        current_timestamp - interval '5 day'
    );

insert into recruit.job_posting_step (
    id,
    job_posting_id,
    step_order,
    step_type,
    title,
    description,
    starts_at,
    ends_at
)
values
    (2001, 1001, 1, 'DOCUMENT', '서류 전형', '지원서와 경력 중심으로 기본 적합도를 검토합니다.', current_timestamp - interval '3 day', current_timestamp + interval '7 day'),
    (2002, 1001, 2, 'INTERVIEW', '1차 인터뷰', '직무 적합도와 협업 방식을 확인하는 실무 인터뷰입니다.', current_timestamp + interval '8 day', current_timestamp + interval '14 day'),
    (2003, 1001, 3, 'INTERVIEW', '2차 인터뷰', '도메인 리더와 시스템 설계 관점을 검증합니다.', current_timestamp + interval '15 day', current_timestamp + interval '18 day'),
    (2004, 1001, 4, 'OFFER', '처우 협의', '최종 합격 후 처우와 입사 일정을 조율합니다.', current_timestamp + interval '19 day', current_timestamp + interval '24 day'),
    (2005, 1002, 1, 'DOCUMENT', '포트폴리오 리뷰', '포트폴리오와 문제 해결 접근을 검토합니다.', current_timestamp - interval '40 day', current_timestamp - interval '30 day'),
    (2006, 1002, 2, 'INTERVIEW', '컬처 인터뷰', '협업 스타일과 커뮤니케이션을 확인합니다.', current_timestamp - interval '29 day', current_timestamp - interval '20 day');

select setval('recruit.job_posting_id_seq', (select max(id) from recruit.job_posting));
select setval('recruit.job_posting_step_id_seq', (select max(id) from recruit.job_posting_step));

