create table recruit.application_submission_request (
    candidate_account_id bigint not null references platform.candidate_account(id) on delete cascade,
    job_posting_id bigint not null references recruit.job_posting(id) on delete cascade,
    idempotency_key varchar(100) not null,
    request_hash char(64) not null,
    application_id bigint references recruit.application(id) on delete cascade,
    created_at timestamptz not null default current_timestamp,
    completed_at timestamptz,
    primary key (candidate_account_id, job_posting_id, idempotency_key)
);

create unique index application_submission_request_application_uidx
    on recruit.application_submission_request(application_id)
    where application_id is not null;

create table recruit.application_event (
    id bigint generated by default as identity primary key,
    application_id bigint not null references recruit.application(id) on delete cascade,
    event_type varchar(60) not null,
    from_state varchar(60),
    to_state varchar(60),
    actor_type varchar(20) not null,
    actor_id bigint,
    reason text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default current_timestamp,
    constraint application_event_actor_type_ck
        check (actor_type in ('CANDIDATE', 'ADMIN', 'SYSTEM'))
);

create index application_event_application_created_idx
    on recruit.application_event(application_id, created_at desc, id desc);
