insert into platform.permission (code, name)
values ('DATA_PRIVACY_MANAGE', 'Candidate Data Privacy Manage')
on conflict (code) do nothing;

insert into platform.role_permission (role, permission_id)
select 'SUPER_ADMIN', id
from platform.permission
where code = 'DATA_PRIVACY_MANAGE'
on conflict (role, permission_id) do nothing;

create table platform.candidate_data_request (
    id bigint generated by default as identity primary key,
    candidate_account_id bigint not null references platform.candidate_account(id) on delete cascade,
    request_type varchar(30) not null,
    status varchar(20) not null,
    candidate_message text,
    resolution_note text,
    reviewed_by bigint references platform.admin_account(id),
    requested_at timestamptz not null default current_timestamp,
    reviewed_at timestamptz,
    completed_at timestamptz,
    cancelled_at timestamptz,
    updated_at timestamptz not null default current_timestamp,
    constraint candidate_data_request_type_ck
        check (request_type in ('DATA_EXPORT', 'DATA_DELETION')),
    constraint candidate_data_request_status_ck
        check (status in ('REQUESTED', 'IN_REVIEW', 'COMPLETED', 'REJECTED', 'CANCELLED'))
);

create unique index candidate_data_request_active_uidx
    on platform.candidate_data_request(candidate_account_id, request_type)
    where status in ('REQUESTED', 'IN_REVIEW');

create index candidate_data_request_admin_queue_idx
    on platform.candidate_data_request(status, requested_at, id);

create table platform.candidate_data_request_event (
    id bigint generated by default as identity primary key,
    request_id bigint not null references platform.candidate_data_request(id) on delete cascade,
    from_status varchar(20),
    to_status varchar(20) not null,
    actor_type varchar(20) not null,
    actor_id bigint,
    note text,
    created_at timestamptz not null default current_timestamp,
    constraint candidate_data_request_event_actor_ck
        check (actor_type in ('CANDIDATE', 'ADMIN', 'SYSTEM'))
);

create index candidate_data_request_event_request_idx
    on platform.candidate_data_request_event(request_id, created_at, id);
