alter table recruit.application
    add column assigned_admin_id bigint references platform.admin_account(id) on delete set null;

create index application_assigned_admin_idx
    on recruit.application(assigned_admin_id);

create table recruit.applicant_tag (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    normalized_name varchar(80) not null unique,
    created_by bigint not null references platform.admin_account(id),
    created_at timestamptz not null default current_timestamp
);

create table recruit.application_tag (
    id bigint generated by default as identity primary key,
    application_id bigint not null references recruit.application(id) on delete cascade,
    tag_id bigint not null references recruit.applicant_tag(id),
    created_by bigint not null references platform.admin_account(id),
    created_at timestamptz not null default current_timestamp,
    constraint application_tag_uidx unique (application_id, tag_id)
);

create index application_tag_tag_idx
    on recruit.application_tag(tag_id, application_id);
