create table platform.admin_applicant_saved_search (
    id bigint generated by default as identity primary key,
    admin_account_id bigint not null references platform.admin_account(id) on delete cascade,
    name varchar(80) not null,
    normalized_name varchar(80) not null,
    filters jsonb not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint admin_applicant_saved_search_name_uidx unique (admin_account_id, normalized_name)
);

create index admin_applicant_saved_search_owner_idx
    on platform.admin_applicant_saved_search(admin_account_id, created_at desc);
