create table recruit.scorecard_criterion (
    id bigint generated by default as identity primary key,
    job_posting_step_id bigint not null references recruit.job_posting_step(id) on delete cascade,
    name varchar(120) not null,
    normalized_name varchar(120) not null,
    description varchar(500),
    weight smallint not null,
    required boolean not null default true,
    sort_order smallint not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint scorecard_criterion_weight_ck check (weight between 1 and 100),
    constraint scorecard_criterion_order_ck check (sort_order >= 0),
    constraint scorecard_criterion_name_uidx unique (job_posting_step_id, normalized_name),
    constraint scorecard_criterion_order_uidx unique (job_posting_step_id, sort_order)
);

create index scorecard_criterion_step_idx
    on recruit.scorecard_criterion(job_posting_step_id, sort_order, id);

insert into recruit.scorecard_criterion (
    job_posting_step_id,
    name,
    normalized_name,
    description,
    weight,
    required,
    sort_order
)
select
    step.id,
    criterion.name,
    lower(criterion.name),
    criterion.description,
    criterion.weight,
    true,
    criterion.sort_order
from recruit.job_posting_step step
cross join (
    values
        ('Role expertise', 'Evidence of the knowledge and skills required for the role.', 40::smallint, 0::smallint),
        ('Problem solving', 'Quality of reasoning, judgment, and problem-solving approach.', 35::smallint, 1::smallint),
        ('Collaboration', 'Communication, ownership, and cross-functional collaboration.', 25::smallint, 2::smallint)
) as criterion(name, description, weight, sort_order)
where step.step_type = 'INTERVIEW';

create table recruit.evaluation_criterion_score (
    id bigint generated by default as identity primary key,
    evaluation_id bigint not null references recruit.evaluation(id) on delete cascade,
    criterion_id bigint not null references recruit.scorecard_criterion(id),
    score smallint not null,
    comment varchar(1000),
    created_at timestamptz not null default current_timestamp,
    constraint evaluation_criterion_score_value_ck check (score between 1 and 5),
    constraint evaluation_criterion_score_uidx unique (evaluation_id, criterion_id)
);

create index evaluation_criterion_score_evaluation_idx
    on recruit.evaluation_criterion_score(evaluation_id, criterion_id);
