create table recruit.notification_template (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    type varchar(40) not null,
    title_template varchar(200) not null,
    content_template text not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create index notification_template_active_idx
    on recruit.notification_template(active, type, name, id);

insert into recruit.notification_template (
    code,
    name,
    type,
    title_template,
    content_template
)
values
    (
        'GENERAL_STATUS_UPDATE',
        '지원 현황 안내',
        'GENERAL',
        '[{jobPostingTitle}] 지원 현황 안내',
        E'안녕하세요, {candidateName}님.\n\n{jobPostingTitle} 지원 현황을 안내드립니다.\n\n감사합니다.'
    ),
    (
        'INTERVIEW_INVITATION',
        '면접 일정 안내',
        'INTERVIEW_INVITE',
        '[{jobPostingTitle}] 면접 일정 안내',
        E'안녕하세요, {candidateName}님.\n\n{jobPostingTitle} 면접 일정이 확정되었습니다. 아래 안내된 일정과 준비 사항을 확인해 주세요.\n\n감사합니다.'
    ),
    (
        'OFFER_NOTICE',
        '채용 제안 안내',
        'OFFER',
        '[{jobPostingTitle}] 채용 제안 안내',
        E'안녕하세요, {candidateName}님.\n\n{jobPostingTitle} 전형 결과 채용 제안을 드립니다. 상세 조건과 회신 방법을 확인해 주세요.\n\n감사합니다.'
    ),
    (
        'REJECTION_NOTICE',
        '전형 결과 안내',
        'REJECTION',
        '[{jobPostingTitle}] 전형 결과 안내',
        E'안녕하세요, {candidateName}님.\n\n{jobPostingTitle} 전형에 참여해 주셔서 감사합니다. 신중한 검토 결과 이번 전형에서는 함께하기 어렵게 되었습니다.\n\n지원해 주신 시간과 관심에 감사드립니다.'
    );

alter table recruit.notification_log
    add column template_id bigint references recruit.notification_template(id) on delete set null,
    add column manual_retry_count integer not null default 0,
    add constraint notification_log_manual_retry_count_ck check (manual_retry_count >= 0);
