alter table platform.candidate_account
    add column email_verified_at timestamptz;

update platform.candidate_account
set email_verified_at = created_at
where email_verified_at is null;

create table platform.candidate_auth_token (
    id bigint generated by default as identity primary key,
    candidate_account_id bigint not null references platform.candidate_account(id) on delete cascade,
    purpose varchar(30) not null,
    token_hash char(64) not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    constraint candidate_auth_token_purpose_ck
        check (purpose in ('EMAIL_VERIFICATION', 'PASSWORD_RESET'))
);

create index candidate_auth_token_active_idx
    on platform.candidate_auth_token(candidate_account_id, purpose, expires_at desc)
    where used_at is null;

create table platform.candidate_auth_mail_outbox (
    id bigint generated by default as identity primary key,
    candidate_account_id bigint not null references platform.candidate_account(id) on delete cascade,
    purpose varchar(30) not null,
    recipient_email varchar(160) not null,
    subject varchar(200) not null,
    content text,
    delivery_status varchar(20) not null default 'PENDING',
    delivery_attempts integer not null default 0,
    next_attempt_at timestamptz default current_timestamp,
    delivered_at timestamptz,
    last_error text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint candidate_auth_mail_purpose_ck
        check (purpose in ('EMAIL_VERIFICATION', 'PASSWORD_RESET')),
    constraint candidate_auth_mail_status_ck
        check (delivery_status in ('PENDING', 'DELIVERED', 'FAILED')),
    constraint candidate_auth_mail_attempts_ck check (delivery_attempts >= 0)
);

create index candidate_auth_mail_dispatch_idx
    on platform.candidate_auth_mail_outbox(delivery_status, next_attempt_at, created_at)
    where delivery_status in ('PENDING', 'FAILED');
