create schema if not exists platform;

create table if not exists platform.admin_account (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    display_name varchar(120) not null,
    password_hash text not null,
    role varchar(40) not null,
    active boolean not null default true,
    last_authenticated_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint admin_account_role_ck check (role in ('ADMIN', 'SUPER_ADMIN'))
);
