create table platform.admin_session (
    id bigint generated by default as identity primary key,
    admin_account_id bigint not null references platform.admin_account(id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamptz not null,
    last_seen_at timestamptz,
    invalidated_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create index admin_session_admin_account_idx
    on platform.admin_session(admin_account_id);

create index admin_session_expires_idx
    on platform.admin_session(expires_at);
