create table recruit.application_attachment (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    file_name       varchar(255) not null,
    original_name   varchar(255) not null,
    content_type    varchar(100) not null,
    file_size       bigint not null,
    storage_path    text not null,
    created_at      timestamptz not null default current_timestamp
);

create index application_attachment_app_idx
    on recruit.application_attachment(application_id);
