create table recruit.application_attachment (
    id bigint generated by default as identity primary key,
    application_id bigint not null references recruit.application(id) on delete cascade,
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null,
    content_type varchar(120) not null,
    file_size_bytes bigint not null,
    storage_path text not null,
    uploaded_at timestamptz not null default current_timestamp,
    constraint application_attachment_size_ck check (file_size_bytes > 0 and file_size_bytes <= 10485760)
);

create index application_attachment_application_id_idx
    on recruit.application_attachment(application_id);
