create table recruit.application_education (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    school_name     varchar(200) not null,
    major           varchar(200),
    degree          varchar(40),
    graduated_at    date,
    sort_order      smallint not null default 0,
    constraint application_education_degree_ck
        check (degree in ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE'))
);

create index application_education_app_idx
    on recruit.application_education(application_id);

create table recruit.application_career (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    company_name    varchar(200) not null,
    position        varchar(200),
    started_at      date not null,
    ended_at        date,
    description     text,
    sort_order      smallint not null default 0
);

create index application_career_app_idx
    on recruit.application_career(application_id);

alter table recruit.application
    add column introduction text,
    add column core_strength text,
    add column career_years integer;
