create table recruit.application_education (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    school_name     varchar(200) not null,
    major           varchar(200),
    degree          varchar(40),
    graduated_at    date,
    sort_order      smallint not null default 0,
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp,
    constraint application_education_degree_ck
        check (degree in ('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE'))
);

create index application_education_app_idx
    on recruit.application_education(application_id);

create table recruit.application_experience (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    company         varchar(200) not null,
    position        varchar(200),
    start_date      date,
    end_date        date,
    description     text,
    sort_order      int not null default 0,
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp
);

create index application_experience_app_idx
    on recruit.application_experience(application_id);

create table recruit.application_skill (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    skill_name      varchar(100) not null,
    proficiency     varchar(30),
    years           int,
    sort_order      int not null default 0,
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp
);

create index application_skill_app_idx
    on recruit.application_skill(application_id);

create table recruit.application_certification (
    id                  bigint generated by default as identity primary key,
    application_id      bigint not null references recruit.application(id) on delete cascade,
    certification_name  varchar(200) not null,
    issuer              varchar(200),
    issued_date         date,
    expiry_date         date,
    sort_order          int not null default 0,
    created_at          timestamptz not null default current_timestamp,
    updated_at          timestamptz not null default current_timestamp
);

create index application_certification_app_idx
    on recruit.application_certification(application_id);

create table recruit.application_language (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null references recruit.application(id) on delete cascade,
    language_name   varchar(60) not null,
    proficiency     varchar(30),
    test_name       varchar(100),
    test_score      varchar(40),
    sort_order      int not null default 0,
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz not null default current_timestamp
);

create index application_language_app_idx
    on recruit.application_language(application_id);

alter table recruit.application
    add column introduction text,
    add column core_strength text,
    add column career_years integer;
